### ISSUE TITLE
Initial publishing does not work

### ISSUE THREAD

**Issue by Vampire** [rodm/gradle-teamcity-plugin#50]
If you try to publish a new plugin, you get a very cryptic 404 problem that is not really obvious what the cause is:
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':server:publishPlugin'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:151)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:148)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:141)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.StartSnapshotTaskInputsBuildOperationTaskExecuter.execute(StartSnapshotTaskInputsBuildOperationTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Failed to upload plugin
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.github.rodm.teamcity.tasks.PublishTask.publishPlugin(PublishTask.groovy:126)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:702)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:669)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:404)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:393)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:376)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:213)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:201)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:77)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:120)
        ... 36 more
Caused by: org.jetbrains.intellij.pluginRepository.exceptions.UploadFailedException:
<!doctype html>
<html lang="en">
<head>









<title>Error 404: Page Not Found</title>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="shortcut icon" href="https://resources.jetbrains.com/storage/ui/favicons/favicon.ico" type="image/x-icon" sizes="16x16 32x32"/>
<link rel="apple-touch-icon" sizes="57x57" href="https://resources.jetbrains.com/storage/ui/favicons/apple-touch-icon-57x57.png"/>
<link rel="apple-touch-icon" sizes="60x60" href="https://resources.jetbrains.com/storage/ui/favicons/apple-touch-icon-60x60.png"/>
<link rel="apple-touch-icon" sizes="72x72" href="https://resources.jetbrains.com/storage/ui/favicons/apple-touch-icon-72x72.png"/>
<link rel="apple-touch-icon" sizes="76x76" href="https://resources.jetbrains.com/storage/ui/favicons/apple-touch-icon-76x76.png"/>
<link rel="apple-touch-icon" sizes="114x114" href="https://resources.jetbrains.com/storage/ui/favicons/apple-touch-icon-114x114.png"/>
<link rel="apple-touch-icon" sizes="120x120" href="https://resources.jetbrains.com/storage/ui/favicons/apple-touch-icon-120x120.png"/>
<link rel="apple-touch-icon" sizes="144x144" href="https://resources.jetbrains.com/storage/ui/favicons/apple-touch-icon-144x144.png"/>
<link rel="apple-touch-icon" sizes="152x152" href="https://resources.jetbrains.com/storage/ui/favicons/apple-touch-icon-152x152.png"/>
<link rel="apple-touch-icon" sizes="180x180" href="https://resources.jetbrains.com/storage/ui/favicons/apple-touch-icon-180x180.png"/>
<link rel="mask-icon" href="https://resources.jetbrains.com/storage/ui/favicons/apple-mask-icon.svg" color="black"/>
<meta name="msapplication-TileColor" content="#000000"/>
<meta name="msapplication-TileImage" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-144x144.png"/>
<meta name="msapplication-square70x70logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-70x70.png"/>
<meta name="msapplication-square150x150logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-150x150.png"/>
<meta name="msapplication-wide310x150logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-310x150.png"/>
<meta name="msapplication-square310x310logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-310x310.png"/>

<!-- Social Media tag Starts -->
<!-- Place this data between the <head> tags of your website -->
<!-- Open Graph data -->
<meta property="og:title" content="Error 404: Page Not Found"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="https://plugins.jetbrains.com/plugin/uploadPlugin"/>
<meta property="og:image" content="https://plugins.jetbrains.com/assets/icons/jetbrains.png"/>
<meta property="og:description" content="Welcome to the JetBrains plugin repository"/>
<meta property="og:site_name" content="JetBrains Plugin Repository"/>
<!-- End Open Graph -->

<!-- Start Twitter Summary Card -->
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@JBPlatform">
<meta name="twitter:image" content="https://plugins.jetbrains.com/assets/icons/jetbrains.png">
<!-- End Twitter Summary Card -->




<meta name="readOnlyModeStatus" content="off">

<link rel="stylesheet" href="/_assets/common.css?ver=6205" type="text/css">
<script src="/_assets/common.js?ver=6205"></script>








  <link rel="stylesheet" href="/_assets/error.css" type="text/css">
  <script src="/_assets/error.js"></script>


</head>

<body id="unknown" class="">

  <!-- Google Tag Manager -->
  <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-5P98" height="0" width="0"
                    style="display:none;visibility:hidden"></iframe></noscript>
  <script>(function (w, d, s, l, i) {
    w[l] = w[l] || [];
    w[l].push({
      'gtm.start': new Date().getTime(), event: 'gtm.js'
    });
    var f = d.getElementsByTagName(s)[0],
      j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
    j.async = true;
    j.src =
      '//www.googletagmanager.com/gtm.js?id=' + i + dl;
    f.parentNode.insertBefore(j, f);
  })(window, document, 'script', 'dataLayer', 'GTM-5P98');</script>
  <!-- End Google Tag Manager -->



<div class="wt-layout">

  <div class="wt-layout__header">












<header class="header js-header-popover-group">
  <div class="wt-container">
    <div class="wt-row wt-row_size_m wt-row_align-items_stretch wt-row_nowrap wt-row_justify_between">
      <div class="wt-col-2 header-logo-wrapper">
          <a class="header-logo jetbrains-logo _logo-jetbrains" href="/"></a>
      </div>

      <nav class="wt-col-inline header-link-list header-link-list-main _align-center hidden-md">
        <a data-popover-group-button-id="nav-intellij"
           class="js-header-popover-hover header-link-item-main">
          <span>IDEs</span>
        </a>

        <a data-popover-group-button-id="nav-dotnet"
           class="js-header-popover-hover header-link-item-main">
          <span>.NET</span>
        </a>

        <a data-popover-group-button-id="nav-teamware"
           class="js-header-popover-hover header-link-item-main">
          <span>Team Tools</span>
        </a>

        <a data-popover-group-button-id="nav-dev-guide"
           class="js-header-popover-hover header-link-item-main">
          <span>Dev Guide</span>
        </a>
      </nav>

      <nav class="wt-col-3 header-link-list header-link-list-main _align-right hidden-md">

          <div class="">
            <a href="/login?request_credentials=required" class="header-link-item-main _simple _icon-wrapper " data-test="signin-button">
              <span class="header-link-item__icon _icon-left icon icon-account-white"></span>
              Sign In
            </a>
          </div>



        <button class="js-header-popover-click header-link-item-main reset-button"
                data-popover-group-button-id="header-search">
          <span class="header-link-item__icon icon icon-search-white"></span>
        </button>
      </nav>
    </div>
  </div>
</header>

<button class="js-header-popover-click header__hamburger hamburger _white _type-close reset-button hidden visible-md"
        data-popover-group-button-id="header-mobile-nav">
  <span class="hamburger__icon"></span>
</button>

<div class="header-placeholder"></div>

<div class="header-popover-content-wrapper" data-popover-group-content-id="header-mobile-nav">

  <div class="header-popover-content header-search-container no-margin-left no-margin-right"
       data-popover-group-content-id="header-search">
    <div class="wt-container">
      <form action="/search?pr=&id=searchHeader" method="get" class="header-search-container__form" >
        <input type="hidden" name="correctionAllowed" value="true">

        <input type="hidden" name="pr" value="">

        <input id="searchInputHeader" class="ja-header-search-input header-search-container__input"
               type="search"
               name="search"
               value=""
               autocomplete="off"
               placeholder="Search 4415 plugins" />

        <button type="submit" class="header-search-container__button button">
          <span class="icon icon-search-gray hidden visible-md"></span>
          Search
        </button>
        <button class="js-close-mobile-nav-button close-mobile-nav-button reset-button hidden visible-md"><span class="icon icon-close"></span></button>
      </form>
    </div>
  </div>

  <div class="header-popover-content" data-popover-group-content-id="nav-intellij">
    <div class="wt-container">
      <div class="wt-row wt-row_size_m wt-row_nowrap">
        <div class="wt-col-3 hidden-md">
          <a href="/plugin/add#intellij"
             class="header-container-description">
            <div class="header-container-description__logo">
              <span class="icon icon-upload"></span>
            </div>

            <div class="header-container-description__title">Upload your plugin</div>

            <div class="header-container-description__text">Your plugin for one of our IDEs might be of great use to millions of users.</div>

            <div class="header-container-description__link">Upload</div>
          </a>
        </div>

        <div class="wt-col-inline wt-col-md-12 wt-offset-left-md-0">
          <span class="header-second-title">IDEs</span>
          <ul class="header-second-links-list _ides">



              <li class="header-second-links-list__item">
                <div class="header-link-item-second &#39;&#39;">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-intellij-idea _full-block"></span>
                  </span>
                  IntelliJ IDEA
                </div>

                <ul class="header-second-links-list">

                    <li class="header-second-links-list__item">
                      <a href="/idea" class="header-link-item-second _font-weight-light ">
                        Ultimate
                      </a>
                    </li>

                    <li class="header-second-links-list__item">
                      <a href="/idea_ce" class="header-link-item-second _font-weight-light ">
                        Community
                      </a>
                    </li>

                    <li class="header-second-links-list__item">
                      <a href="/idea_edu" class="header-link-item-second _font-weight-light ">
                        Educational
                      </a>
                    </li>

                </ul>
              </li>



              <li class="header-second-links-list__item">
                <div class="header-link-item-second &#39;&#39;">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-pycharm _full-block"></span>
                  </span>
                  PyCharm
                </div>

                <ul class="header-second-links-list">

                    <li class="header-second-links-list__item">
                      <a href="/pycharm" class="header-link-item-second _font-weight-light ">
                        Professional
                      </a>
                    </li>

                    <li class="header-second-links-list__item">
                      <a href="/pycharm_ce" class="header-link-item-second _font-weight-light ">
                        Community
                      </a>
                    </li>

                    <li class="header-second-links-list__item">
                      <a href="/pycharm_edu" class="header-link-item-second _font-weight-light ">
                        Educational
                      </a>
                    </li>

                </ul>
              </li>



              <li class="header-second-links-list__item">
                <a href="/phpstorm" class="header-link-item-second ">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-phpstorm _full-block"></span>
                  </span>
                  PhpStorm
                </a>
              </li>

              <li class="header-second-links-list__item">
                <a href="/webstorm" class="header-link-item-second ">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-webstorm _full-block"></span>
                  </span>
                  WebStorm
                </a>
              </li>

              <li class="header-second-links-list__item">
                <a href="/ruby" class="header-link-item-second ">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-rubymine _full-block"></span>
                  </span>
                  RubyMine
                </a>
              </li>

              <li class="header-second-links-list__item">
                <a href="/objc" class="header-link-item-second ">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-appcode _full-block"></span>
                  </span>
                  AppCode
                </a>
              </li>

              <li class="header-second-links-list__item">
                <a href="/clion" class="header-link-item-second ">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-clion _full-block"></span>
                  </span>
                  CLion
                </a>
              </li>

              <li class="header-second-links-list__item">
                <a href="/go" class="header-link-item-second ">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-gogland _full-block"></span>
                  </span>
                  GoLand
                </a>
              </li>

              <li class="header-second-links-list__item">
                <a href="/dbe" class="header-link-item-second ">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-datagrip _full-block"></span>
                  </span>
                  DataGrip
                </a>
              </li>

              <li class="header-second-links-list__item">
                <a href="/rider" class="header-link-item-second ">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-rider _full-block"></span>
                  </span>
                  Rider
                </a>
              </li>

              <li class="header-second-links-list__item">
                <a href="/mps" class="header-link-item-second ">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-mps _full-block"></span>
                  </span>
                  MPS
                </a>
              </li>

              <li class="header-second-links-list__item">
                <a href="/androidstudio" class="header-link-item-second ">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-androidstudio _full-block"></span>
                  </span>
                  Android Studio
                </a>
              </li>

          </ul>
        </div>

        <div class="wt-col-inline wt-offset-left-2 hidden-md">
          <ul>
            <li class="header-second-links-list__item" id="rc-intellij-contest-link"></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="header-popover-content" data-popover-group-content-id="nav-dotnet">
    <div class="wt-container">
      <div class="wt-row wt-row_size_m wt-row_nowrap">
        <div class="wt-col-3 hidden-lg">
          <a href="/plugin/add#dotnet"
             class="header-container-description">

            <div class="header-container-description__logo">
              <span class="icon icon-upload"></span>
            </div>

            <div class="header-container-description__title">Upload your plugin</div>

            <div class="header-container-description__text">
              Your plugin for one of our .NET tools might be of great use to millions of users.
            </div>

            <div class="header-container-description__link">Upload</div>
          </a>
        </div>

        <div class="wt-col-inline wt-offset-left-lg-2 wt-col-md-12 wt-offset-left-md-0">
          <span class="header-second-title">Team Tools</span>
          <ul class="header-second-links-list _team-tools">

              <li class="header-second-links-list__item">
                <a href="/resharper" class="header-link-item-second ">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-resharper _full-block"></span>
                  </span>
                  ReSharper
                </a>
              </li>

              <li class="header-second-links-list__item">
                <a href="/rider" class="header-link-item-second ">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-rider _full-block"></span>
                  </span>
                  Rider
                </a>
              </li>

          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="header-popover-content" data-popover-group-content-id="nav-teamware">
    <div class="wt-container">
      <div class="wt-row wt-row_size_m wt-row_nowrap">
        <div class="wt-col-3 hidden-md">
          <a href="/plugin/add#teamcity"
             class="header-container-description">

            <div class="header-container-description__logo">
              <span class="icon icon-upload"></span>
            </div>

            <div class="header-container-description__title">Upload your plugin</div>

            <div class="header-container-description__text">Your plugin for one of our team tools might be of great use to millions of users.</div>

            <div class="header-container-description__link">Upload</div>
          </a>
        </div>

        <div class="wt-col-inline wt-offset-left-1 wt-col-md-12 wt-offset-left-md-0">
          <span class="header-second-title">Team Tools</span>
          <ul class="header-second-links-list _team-tools">

              <li class="header-second-links-list__item">
                <a href="/teamcity" class="header-link-item-second ">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-teamcity _full-block"></span>
                  </span>
                  TeamCity
                </a>
              </li>

              <li class="header-second-links-list__item">
                <a href="/hub" class="header-link-item-second ">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-hub _full-block"></span>
                  </span>
                  Hub
                </a>
              </li>

              <li class="header-second-links-list__item">
                <a href="/youtrack" class="header-link-item-second ">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-youtrack _full-block"></span>
                  </span>
                  YouTrack
                </a>
              </li>

              <li class="header-second-links-list__item">
                <a href="/upsource" class="header-link-item-second ">
                  <span class="header-link-item-second__logo">
                    <span class="jetbrains-logo _logo-upsource _full-block"></span>
                  </span>
                  Upsource
                </a>
              </li>

          </ul>
        </div>

        <div class="wt-col-inline hidden-md">
          <ul>
            <li class="header-second-links-list__item" id="rc-teamcity-contest-link"></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="header-popover-content" data-popover-group-content-id="nav-dev-guide">
    <div class="wt-container">
      <div class="wt-row wt-row_size_m wt-row_nowrap">
        <div class="wt-col-inline wt-offset-left-6 wt-col-md-12 wt-offset-left-md-0">
          <span class="header-second-title">Dev Guide</span>
          <ul class="header-second-links-list _dev-guide">
            <li class="header-second-links-list__item">
              <a class="header-link-item-second"
                 href="//www.jetbrains.org/intellij/sdk/docs/">
                IntelliJ Platform SDK
              </a>
            </li>
            <li class="header-second-links-list__item">
              <a class="header-link-item-second" href="//plugins.jetbrains.com/docs/teamcity/">TeamCity plugins</a>
            </li>
            <li class="header-second-links-list__item">
              <a class="header-link-item-second"
                 href="//www.jetbrains.com/help/hub/building-custom-widgets.html">
                Hub custom widgets
              </a>
            </li>
            <li class="header-second-links-list__item">
              <a class="header-link-item-second"
                 href="//www.jetbrains.com/help/resharper/sdk/">
                R# plugins
              </a>
            </li>
            <li class="header-second-links-list__item">
              <a class="header-link-item-second"
                 href="/marketplace">
                Marketplace EAP
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

    <div class="wt-container">
      <div class="header-popover-content _profile float-right float-none-md"
           data-popover-group-content-id="nav-user">

          <a href="/login?request_credentials=required" class="header-second-title ">
            Sign In
          </a>



      </div>
    </div>
</div>

  </div>

  <div class="wt-layout__content">

    <div class="wt-container">

<div class="page-error__content">
  <div class="wt-row wt-row_size_m wt-row_justify_center wt-row-sm_justify_start">
    <div class="wt-col-3 wt-col-lg-4 wt-col-md-5 ">
      <div class="page-error-logo _error-404">
        <div class="page-error-logo__beam"></div>
      </div>
    </div>

    <div class="wt-col-5 wt-col-md-7 wt-col-sm-12 article-content">
      <h1 class="page-error__h1 _big">uh-oh!</h1>

      <div class="page-error__sub-title sub-title">You surely know what this means.</div>

      <div class="page-error__text">
        We can't find the page you're looking for. Try starting from <a href="/">home</a>.
      </div>
    </div>
  </div>
</div>

    </div>

  </div>
  <footer class="wt-layout__footer">

<div class="wt-container">
  <div class="footer wt-text-3">
    <div class="footer__column footer__column_left">
      <a href="https://www.jetbrains.com" class="footer__logo">
        <div class="jetbrains-logo _logo-jetbrains-square"></div>
      </a>

      <div class="footer__info">
        <p>Copyright &copy; 2000û<span class="js-footer-current-year"></span> JetBrains s.r.o.</p>
        <p>Developed with drive and <a class="wt-link" href="https://www.jetbrains.com/idea">IntelliJ IDEA</a></p>
        <p class="footer__build-number">Build #6205</p>
      </div>
    </div>

    <div class="footer__column footer__column_right">
      <ul class="footer__list footer__list_align_right">
        <li><a class="wt-link" href="mailto:plugins-admin@jetbrains.com">Feedback</a></li>
        <li><a class="wt-link" href="https://twitter.com/JBPlatform">Twitter</a></li>
        <li><a class="wt-link" href="https://blog.jetbrains.com/platform">Blog</a></li>
        <li><a class="wt-link" href="/marketplace">Marketplace</a></li>
      </ul>
      <ul class="footer__list footer__list_align_right">
        <li><a class="wt-link wt-link_color_inherit" href="/legal/terms-of-use">Terms of Use</a></li>
        <li><a class="wt-link wt-link_color_inherit" href="/legal">Legal, Privacy & Security</a></li>
      </ul>
    </div>
  </div>
</div>

  </footer>
</div>

<div class="js-notifications-container"></div>
<div class="js-overlay overlay"></div>
</body>
</html>



        at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.uploadPluginInternal(pluginRepositoryRest.kt:123)
        at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.uploadPluginInternal$default(pluginRepositoryRest.kt:108)
        at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.uploadPlugin(pluginRepositoryRest.kt:105)
        at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance$uploadPlugin.call(Unknown Source)
        at com.github.rodm.teamcity.tasks.PublishTask.publishPlugin(PublishTask.groovy:122)
        ... 91 more
```

I think the problem is the one reported at https://github.com/JetBrains/plugin-repository-rest-client/issues/11 and at least improved with a meaningful error message at https://github.com/JetBrains/plugin-repository-rest-client/pull/26/files, so you should probably upgrade to the latest version of that lib to benefit from the better error message.

**Comment by rodm** [comment]
I also updated the readme to indicate that the first upload needs to be done via the website.
